# Generated by Django 2.2.3 on 2019-07-08 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendance for', models.DateField()),
                ('is_present', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.CharField(max_length=1)),
                ('female', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('first', models.CharField(max_length=30)),
                ('last', models.CharField(max_length=30)),
                ('Date of birth', models.DateField()),
                ('cnic', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attendance.Person')),
            ],
            bases=('attendance.person',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attendance.Person')),
            ],
            bases=('attendance.person',),
        ),
        migrations.CreateModel(
            name='TeacherAttendace',
            fields=[
                ('attendance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attendance.Attendance')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Teacher')),
            ],
            bases=('attendance.attendance',),
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('attendance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attendance.Attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student')),
            ],
            bases=('attendance.attendance',),
        ),
    ]
