# Generated by Django 2.2.3 on 2019-07-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='female',
            new_name='gender_info',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='male',
        ),
    ]
